# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Inherit system defaults
source /etc/profile

# don't put duplicate lines in the history
export HISTCONTROL=ignoredups

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

export EDITOR=vim

# Prompt "vstinner@apu$ "
export PS1='\u@\h$ '

if [ -e /etc/bash_completion ]; then
    # bash_completion doesn't support noclobber
    set +C
    source /etc/bash_completion
fi

if [ "$(uname -s)" = "FreeBSD" ]; then
    # On FreeBSD, define CFLAGS variable as an empty string to prevent make
    # to add -O2 flag when building Python in debug mode (-O0)
    export CFLAGS=
    export LC_ALL="fr_FR.UTF-8"

    alias ls='ls -F -G'
    alias rm='rm -i -x'
else
    alias ls='ls -F --color=auto'
    alias rm='rm -i --one-file-system'
fi

alias ln="ln -i -v"
alias cp='cp -i -v'
alias mv='mv -i -v'
alias tar='tar -k'
alias du='du -h'
alias df='df -h'
alias grep='grep --color'
alias nssh='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
alias nscp='scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
#alias cat='cat -v'

# Protect myself against stupid commands like "echo user:password: >/etc/passwd"
set -C

export MAKEFLAGS=$(python3 -c "import os; print('-j%s' % (os.cpu_count() + 2))")

# ~/.local/bin/ is used by pip, systemd and is an extendsion
# of XDG user-dirs specs
export PATH=~/.local/bin:$PATH

# Disable CTRL+s shortcut (freeze the terminal, use CTRL+q to unfreeze)
# to get readline CTRL+s shortcut (search forward in the history)
stty -ixon

# Use -C to use a config.cache in the current directory
alias configure="./configure -C"

# configure to compile Python in debug mode.
# - use -C to use a config.cache in the current directory
# - force -O0 (instead of -Og) for best debug experience (in gdb)
# - use --with-pydebug to compile python in debug mode.
alias pyconfigure_debug="./configure -C --with-pydebug CFLAGS=-O0"

HOSTNAME=$(hostname)
if [ "$HOSTNAME" = "selma" -o "$HOSTNAME" = "apu" ]; then
    # Based on ~/.config/systemd/user/ssh-agent.service
    export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
fi

# Red Hat qa-tools package sets PYTHONPATH
unset PYTHONPATH
